In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("career_path_in_all_field.csv")

In [3]:
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns

print(numerical_columns)

Index(['GPA', 'Extracurricular_Activities', 'Internships', 'Projects',
       'Leadership_Positions', 'Field_Specific_Courses', 'Research_Experience',
       'Coding_Skills', 'Communication_Skills', 'Problem_Solving_Skills',
       'Teamwork_Skills', 'Analytical_Skills', 'Presentation_Skills',
       'Networking_Skills', 'Industry_Certifications'],
      dtype='object')

In [4]:
df[numerical_columns].mean()

GPA                           3.740375
Extracurricular_Activities    4.514556
Internships                   0.999778
Projects                      2.009556
Leadership_Positions          0.509778
Field_Specific_Courses        4.500333
Research_Experience           0.506556
Coding_Skills                 2.010111
Communication_Skills          1.987444
Problem_Solving_Skills        2.011111
Teamwork_Skills               2.009556
Analytical_Skills             2.005111
Presentation_Skills           1.984111
Networking_Skills             1.989444
Industry_Certifications       0.497667
dtype: float64

In [5]:
df[numerical_columns].median()

GPA                           3.739713
Extracurricular_Activities    5.000000
Internships                   1.000000
Projects                      2.000000
Leadership_Positions          1.000000
Field_Specific_Courses        4.000000
Research_Experience           1.000000
Coding_Skills                 2.000000
Communication_Skills          2.000000
Problem_Solving_Skills        2.000000
Teamwork_Skills               2.000000
Analytical_Skills             2.000000
Presentation_Skills           2.000000
Networking_Skills             2.000000
Industry_Certifications       0.000000
dtype: float64

In [6]:
df[numerical_columns].mode().iloc[0]

GPA                           2.500093
Extracurricular_Activities    7.000000
Internships                   0.000000
Projects                      4.000000
Leadership_Positions          1.000000
Field_Specific_Courses        3.000000
Research_Experience           1.000000
Coding_Skills                 4.000000
Communication_Skills          2.000000
Problem_Solving_Skills        1.000000
Teamwork_Skills               3.000000
Analytical_Skills             3.000000
Presentation_Skills           0.000000
Networking_Skills             3.000000
Industry_Certifications       0.000000
Name: 0, dtype: float64

In [7]:
df[numerical_columns].min()

GPA                           2.500093
Extracurricular_Activities    0.000000
Internships                   0.000000
Projects                      0.000000
Leadership_Positions          0.000000
Field_Specific_Courses        0.000000
Research_Experience           0.000000
Coding_Skills                 0.000000
Communication_Skills          0.000000
Problem_Solving_Skills        0.000000
Teamwork_Skills               0.000000
Analytical_Skills             0.000000
Presentation_Skills           0.000000
Networking_Skills             0.000000
Industry_Certifications       0.000000
dtype: float64

In [8]:
df[numerical_columns].max()

GPA                           4.999803
Extracurricular_Activities    9.000000
Internships                   2.000000
Projects                      4.000000
Leadership_Positions          1.000000
Field_Specific_Courses        9.000000
Research_Experience           1.000000
Coding_Skills                 4.000000
Communication_Skills          4.000000
Problem_Solving_Skills        4.000000
Teamwork_Skills               4.000000
Analytical_Skills             4.000000
Presentation_Skills           4.000000
Networking_Skills             4.000000
Industry_Certifications       1.000000
dtype: float64

In [9]:
df[numerical_columns].max() - df[numerical_columns].min()

GPA                           2.49971
Extracurricular_Activities    9.00000
Internships                   2.00000
Projects                      4.00000
Leadership_Positions          1.00000
Field_Specific_Courses        9.00000
Research_Experience           1.00000
Coding_Skills                 4.00000
Communication_Skills          4.00000
Problem_Solving_Skills        4.00000
Teamwork_Skills               4.00000
Analytical_Skills             4.00000
Presentation_Skills           4.00000
Networking_Skills             4.00000
Industry_Certifications       1.00000
dtype: float64

In [10]:
df[numerical_columns].var()

GPA                           0.517754
Extracurricular_Activities    8.218924
Internships                   0.667407
Projects                      2.023022
Leadership_Positions          0.249932
Field_Specific_Courses        8.282698
Research_Experience           0.249985
Coding_Skills                 2.010899
Communication_Skills          1.991286
Problem_Solving_Skills        1.991653
Teamwork_Skills               1.993686
Analytical_Skills             2.011975
Presentation_Skills           2.014971
Networking_Skills             1.992443
Industry_Certifications       0.250022
dtype: float64

In [11]:
df[numerical_columns].std()

GPA                           0.719551
Extracurricular_Activities    2.866867
Internships                   0.816950
Projects                      1.422330
Leadership_Positions          0.499932
Field_Specific_Courses        2.877968
Research_Experience           0.499985
Coding_Skills                 1.418062
Communication_Skills          1.411129
Problem_Solving_Skills        1.411260
Teamwork_Skills               1.411979
Analytical_Skills             1.418441
Presentation_Skills           1.419497
Networking_Skills             1.411539
Industry_Certifications       0.500022
dtype: float64

In [12]:
df[numerical_columns].corr()

,GPA,Extracurricular_Activities,Internships,Projects,Leadership_Positions,Field_Specific_Courses,Research_Experience,Coding_Skills,Communication_Skills,Problem_Solving_Skills,Teamwork_Skills,Analytical_Skills,Presentation_Skills,Networking_Skills,Industry_Certifications
GPA,1.000000,0.002226,0.007045,0.012624,0.010719,0.010571,-0.009792,-0.010375,-0.026944,0.011723,0.008043,0.005261,0.005005,-0.005330,-0.003756
Extracurricular_Activities,0.002226,1.000000,-0.003415,-0.003986,0.012345,-0.012607,0.004585,-0.004697,0.006926,0.003311,0.025441,0.003698,0.003511,-0.004040,0.008473
Internships,0.007045,-0.003415,1.000000,-0.012813,-0.002171,-0.004017,0.000004,-0.001629,0.003275,0.003472,-0.007512,-0.003451,-0.003069,0.002503,-0.001089
Projects,0.012624,-0.003986,-0.012813,1.000000,-0.000757,0.008550,-0.015089,-0.004841,-0.001380,0.015448,0.006539,0.014186,0.003653,-0.006647,-0.014344
Leadership_Positions,0.010719,0.012345,-0.002171,-0.000757,1.000000,0.004439,-0.010259,-0.000375,-0.013451,-0.000784,0.006479,0.000400,-0.008159,0.005894,0.001203
Field_Specific_Courses,0.010571,-0.012607,-0.004017,0.008550,0.004439,1.000000,-0.001700,-0.002002,0.008497,0.007249,-0.002325,-0.004873,0.003551,-0.001928,0.016371
Research_Experience,-0.009792,0.004585,0.000004,-0.015089,-0.010259,-0.001700,1.000000,-0.002366,0.000510,-0.000576,0.004633,-0.006785,0.001164,0.002539,-0.006162
Coding_Skills,-0.010375,-0.004697,-0.001629,-0.004841,-0.000375,-0.002002,-0.002366,1.000000,0.005283,-0.015715,-0.021027,-0.007760,-0.001300,-0.012382,0.013433
Communication_Skills,-0.026944,0.006926,0.003275,-0.001380,-0.013451,0.008497,0.000510,0.005283,1.000000,-0.001939,-0.010090,0.004140,-0.007311,-0.000401,0.013109
Problem_Solving_Skills,0.011723,0.003311,0.003472,0.015448,-0.000784,0.007249,-0.000576,-0.015715,-0.001939,1.000000,0.018071,-0.002249,0.004027,0.010658,-0.007365
Teamwork_Skills,0.008043,0.025441,-0.007512,0.006539,0.006479,-0.002325,0.004633,-0.021027,-0.010090,0.018071,1.000000,-0.003464,0.006008,-0.000786,0.000346
Analytical_Skills,0.005261,0.003698,-0.003451,0.014186,0.000400,-0.004873,-0.006785,-0.007760,0.004140,-0.002249,-0.003464,1.000000,-0.006141,-0.010907,-0.002490
Presentation_Skills,0.005005,0.003511,-0.003069,0.003653,-0.008159,0.003551,0.001164,-0.001300,-0.007311,0.004027,0.006008,-0.006141,1.000000,-0.010510,0.011142
Networking_Skills,-0.005330,-0.004040,0.002503,-0.006647,0.005894,-0.001928,0.002539,-0.012382,-0.000401,0.010658,-0.000786,-0.010907,-0.010510,1.000000,0.005397
Industry_Certifications,-0.003756,0.008473,-0.001089,-0.014344,0.001203,0.016371,-0.006162,0.013433,0.013109,-0.007365,0.000346,-0.002490,0.011142,0.005397,1.000000

In [13]:
df[numerical_columns].describe()

,GPA,Extracurricular_Activities,Internships,Projects,Leadership_Positions,Field_Specific_Courses,Research_Experience,Coding_Skills,Communication_Skills,Problem_Solving_Skills,Teamwork_Skills,Analytical_Skills,Presentation_Skills,Networking_Skills,Industry_Certifications
count,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000
mean,3.740375,4.514556,0.999778,2.009556,0.509778,4.500333,0.506556,2.010111,1.987444,2.011111,2.009556,2.005111,1.984111,1.989444,0.497667
std,0.719551,2.866867,0.816950,1.422330,0.499932,2.877968,0.499985,1.418062,1.411129,1.411260,1.411979,1.418441,1.419497,1.411539,0.500022
min,2.500093,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.105267,2.000000,0.000000,1.000000,0.000000,2.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
50%,3.739713,5.000000,1.000000,2.000000,1.000000,4.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000
75%,4.361090,7.000000,2.000000,3.000000,1.000000,7.000000,1.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,1.000000
max,4.999803,9.000000,2.000000,4.000000,1.000000,9.000000,1.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,1.000000